InsecureWebApp/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MicroFocus.InsecureWebApp.Models;
using MicroFocus.InsecureWebApp.Data;
using Swashbuckle.AspNetCore.Annotations;
using System.IO;
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Net.Http;
using System.Net;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.StaticFiles;

namespace MicroFocus.InsecureWebApp.Controllers
{
    #region ProductsController
    [Route("api/v1/[controller]")]
    [ApiController]
    public class ProductsController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public ProductsController(ApplicationDbContext context)
        {
            _context = context;
        }
        #endregion
        // POST: api/v1/products
        [SwaggerOperation(
            OperationId = "InsertSearchText",
            Description = "Requires user id",
            Summary = "Save Keyword search user wise"
        )]
        [HttpPost("InsertSearchText")]
        public async Task<IActionResult> InsertSearchText(String keywords, string UserId)
        {
            String query = string.Empty;
            await Task.Delay(1);
            if (!String.IsNullOrEmpty(keywords) && (!String.IsNullOrEmpty(UserId)))
            {
                query = "DELETE FROM ProductSearch where UserId='" + UserId + "'; INSERT INTO ProductSearch (SearchText,UserId) VALUES ('" + keywords + "', '" + UserId + "')";
                _context.Product.FromSqlRaw(query);
                //_context.Database.ExecuteSqlRaw(query);
            }
            return Ok(query);
        }

        // GET: api/v1/products
        [SwaggerOperation("GetProducts")]
        [HttpGet("GetProducts")]
        public ActionResult<IEnumerable<Product>> GetProducts(String keywords, long limit = 50)
        {
            /* FvB */
            var query = "SELECT TOP " + Convert.ToInt32(limit) + " *, Description as HtmlContent FROM dbo.Product WHERE (" +
                " Name LIKE '%" + keywords + "%' OR " +
                " Summary LIKE '%" + keywords + "%' OR " +
                " Description LIKE '%" + keywords + "%')";
            try
            {
                var products1 = _context.Product.FromSqlRaw(query);
                //var products1 = _context.Database.ExecuteSqlRaw(query);
            }catch (Exception ex)
            {
                
                // add sensitive data and bubble up exception
                ex.Data.Add("dynamic data", query);

                throw new Exception("Problem building SQL Query:"+query, ex.InnerException);
                //throw ex;
            }
            //return products;
            //var products1 = _context.Product.FromSqlRaw(query);
            /*var products = from p in _context.Product
                           select p;

            if (!String.IsNullOrEmpty(keywords))
            {
                products = products.Where(p => p.Name.Contains(keywords)
                              || p.Summary.Contains(keywords)
                              || p.Description.Contains(keywords));
            }

            if (limit > 0)
            {
                products = products.Take(Convert.ToInt32(limit));
            }
            return await products.AsNoTracking().ToListAsync();*/
            var products = _context.Product.FromSqlRaw("SELECT TOP " + Convert.ToInt32(limit) + " *, Description as HtmlContent FROM dbo.Product WHERE (" +
                " Name LIKE '%" + keywords + "%' OR " +
                " Summary LIKE '%" + keywords + "%' OR " +
                " Description LIKE '%" + keywords + "%')").ToList();
            return products;
        }

        [HttpPost("GetProductFromOtherSource")]
        public async Task<string> GetProductFromOtherSource(string url)
        {
            var httpClientHandler = new HttpClientHandler();
            httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, sslPolicyErrors) =>
            {
                return true;
            };

            string sReturnVal = string.Empty;
            HttpClient client = new HttpClient(httpClientHandler);
            HttpResponseMessage response = await client.GetAsync(url);
            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                var product = await response.Content.ReadAsStringAsync();
                sReturnVal = response.Content.ReadAsStringAsync().Result;

            }
            //dynamic dynJson = JsonConvert.DeserializeObject(sReturnVal).ToString();
            return sReturnVal;
        }

        [SwaggerOperation("ViewPic")]
        [HttpGet("ViewPic")]
        public ActionResult ViewPic(string sFile)
        {

            var fileProvider = new FileExtensionContentTypeProvider();

            //Environment.WebRootPath
            //"~/img/products/"
            //Build the File Path.
            string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot" + Path.DirectorySeparatorChar + "img" + Path.DirectorySeparatorChar + "products" + Path.DirectorySeparatorChar) + sFile;
            
            

            if (!fileProvider.TryGetContentType(Path.GetExtension(path), out string contentType))
            {
                return PhysicalFile(path, "image/jpeg");
            } else
            {
                return PhysicalFile(path, contentType);
            }

            ////Read the File data into Byte Array.
            //byte[] bytes = System.IO.File.ReadAllBytes(path);


            ////Send the File to Download.
            //return PhysicalFile(path, "image/jpeg");
            ////return File(bytes, "image/jpeg", sFile);
            ////return new FileStreamResult(new MemoryStream(bytes), "image/jpeg") { FileDownloadName = sFile };


        }

        [SwaggerOperation("GetTestResponse")]
        [HttpGet("GetTestResponse")]
        public IActionResult GetTestResponse()
        {
            //for testing of XSS purpose
            var response = Content("Test Success !!");
            return Ok(response.Content.ToString());

            //await HttpResponseWritingExtensions.WriteAsync(HttpContext.Response, "Hello World");
            //return Ok(HttpContext.Response);
        }

        #region snippet_GetByID
        // GET: api/v1/products/5
        [SwaggerOperation(OperationId = "GetProductById")]
        [HttpGet("GetProductById/{id}")]
        public async Task<ActionResult<Product>> GetProduct(int id)
        {
            var Product = await _context.Product.FindAsync(id);

            if (Product == null)
            {
                return NotFound();
            }

            return Product;
        }
        [HttpGet("{id}")]
        public async Task<ActionResult<Product>> GetEachProduct(int id)
        {
            var Product = await _context.Product.FindAsync(id);

            if (Product == null)
            {
                return NotFound();
            }

            return Product;
        }
        #endregion

        #region snippet_Update
        // PUT: api/v1/products/5
        [SwaggerOperation(OperationId = "PutProduct")]
        [HttpPut("PutProductById/{id}")]
#pragma warning disable SF8FC171238E9435BBC5E53DF24BB279A // Mass Assignment : Insecure Binder Configuration
        public async Task<IActionResult> PutProduct(int id, Product Product)
#pragma warning restore SF8FC171238E9435BBC5E53DF24BB279A // Mass Assignment : Insecure Binder Configuration
        {
            if (id != Product.ID)
            {
                return BadRequest();
            }

            _context.Entry(Product).State = EntityState.Modified;

            if (await TryUpdateModelAsync<Product>(Product,"", c => c.Code, 
                c => c.Price, 
                c => c.Name, 
                c => c.Description ))
            {
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }

            return NoContent();
        }
        #endregion

        #region snippet_Create
        // POST: api/v1/products
        [SwaggerOperation(OperationId = "PostProduct")]
        [HttpPost("PostProduct")]
#pragma warning disable SF8FC171238E9435BBC5E53DF24BB279A // Mass Assignment : Insecure Binder Configuration
        public async Task<ActionResult<Product>> PostProduct(Product Product)
#pragma warning restore SF8FC171238E9435BBC5E53DF24BB279A // Mass Assignment : Insecure Binder Configuration
        {
            _context.Product.Add(Product);
            await _context.SaveChangesAsync();

            //return CreatedAtAction("GetProduct", new { id = Product.ID }, Product);
            return CreatedAtAction(nameof(GetProduct), new { id = Product.ID }, Product);
        }
        #endregion

        #region snippet_Delete
        // DELETE: api/v1/products/5
        //[Route("DeleteProduct", Name = "DeleteProduct")]
        [SwaggerOperation(OperationId = "DeleteProduct")]
        [HttpDelete("DeleteProduct/{id}")]
        public async Task<ActionResult<Product>> DeleteProduct(int id)
        {
            var Product = await _context.Product.FindAsync(id);
            if (Product == null)
            {
                return NotFound();
            }

            _context.Product.Remove(Product);
            await _context.SaveChangesAsync();

            return Product;
        }
        #endregion

        private bool ProductExists(int id)
        {

InsecureWebApp/Pages/Products/Admin/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MicroFocus.InsecureWebApp.Data;
using MicroFocus.InsecureWebApp.Models;

namespace MicroFocus.InsecureWebApp.Pages.Products
{
    public class CreateModel : PageModel
    {
        private readonly MicroFocus.InsecureWebApp.Data.ApplicationDbContext _context;

        public CreateModel(MicroFocus.InsecureWebApp.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Product Product { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Product.Add(Product);
            await _context.SaveChangesAsync();

            return RedirectToPage("../Index");
        }
    }
}

InsecureWebApp/Pages/Products/Admin/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MicroFocus.InsecureWebApp.Data;
using MicroFocus.InsecureWebApp.Models;

namespace MicroFocus.InsecureWebApp.Pages.Products
{
    public class DeleteModel : PageModel
    {
        private readonly MicroFocus.InsecureWebApp.Data.ApplicationDbContext _context;

        public DeleteModel(MicroFocus.InsecureWebApp.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Product Product { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product = await _context.Product.FirstOrDefaultAsync(m => m.ID == id);

            if (Product == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product = await _context.Product.FindAsync(id);

            if (Product != null)
            {
                _context.Product.Remove(Product);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("../Index");
        }
    }
}

InsecureWebApp/Pages/Products/Admin/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MicroFocus.InsecureWebApp.Data;
using MicroFocus.InsecureWebApp.Models;

namespace MicroFocus.InsecureWebApp.Pages.Products
{
    public class EditModel : PageModel
    {
        private readonly MicroFocus.InsecureWebApp.Data.ApplicationDbContext _context;

        public EditModel(MicroFocus.InsecureWebApp.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Product Product { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product = await _context.Product.FirstOrDefaultAsync(m => m.ID == id);

            if (Product == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Product).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ProductExists(Product.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("../Index");
        }

        private bool ProductExists(int id)
        {
            return _context.Product.Any(e => e.ID == id);
        }
    }
}

InsecureWebApp/Pages/Products/Compare.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;

namespace MicroFocus.InsecureWebApp.Pages.Products
{
    public class CompareModel : PageModel
    {
        private static readonly IConfiguration _iconfiguration;

        public List<MicroFocus.InsecureWebApp.Models.Product> Products { get; set; }
        public string jSonResult { get; set; }

        [TempData]
        public string StatusMessage { get; set; }

        private readonly MicroFocus.InsecureWebApp.Data.ApplicationDbContext _context;

        public CompareModel(MicroFocus.InsecureWebApp.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public string url { get; set; }

        public void OnGetAsync()
        {

        }

        public void OnPost(string url)
        {
            //try
            //{
            //    if (!string.IsNullOrEmpty(url))
            //    {
            //        WebRequest request = WebRequest.Create(url);
            //        WebResponse response = request.GetResponse();
            //        if (response != null)
            //        {
            //            Controllers.ProductsController pc = new Controllers.ProductsController(_context);
            //            var products = await pc.GetProductFromOtherSource(url);
            //            jSonResult = products;
            //            this.url = url;
            //        }
            //    }
            //}
            //catch (Exception ex)
            //{
            //    throw ex;
            //}

        }

        public async Task<IActionResult> OnPostPullProducts(string url)
        {
            var httpClientHandler = new HttpClientHandler();
            httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, sslPolicyErrors) =>
            {
                return true;
            };

            if (!string.IsNullOrEmpty(url))
            {
                this.url = url;
                HttpClient client = new HttpClient(httpClientHandler);
                HttpResponseMessage response = await client.GetAsync(url);
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    Controllers.ProductsController pc = new Controllers.ProductsController(_context);
                    var products = await pc.GetProductFromOtherSource(url);
                    jSonResult = products;
                }
            }
            return null;
        }
    }
}

InsecureWebApp/Pages/Products/Compare.cshtml
@page "{url?}"
@using System.Web
@using MicroFocus.InsecureWebApp.Models
@using Newtonsoft.Json
@using Newtonsoft.Json.Linq
@model MicroFocus.InsecureWebApp.Pages.Products.CompareModel
@{
    ViewData["Title"] = "Compare Products";
    
    //Model.Keywords = HttpUtility.HtmlEncode(Model.Keywords);
}
<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0"><a asp-page="/Products">Shop</a> </div>
        </div>
    </div>
</div>
<div class="site-section-sm">

    <div class="container">

        @{
            string sUrl = Request.Query["url"];
            if (string.IsNullOrEmpty(sUrl))
            {
                Model.url = "https://localhost:5004/api/v1/products?limit=50";
            }
        }
        <div class="row mb-1">
            <form class="col-md-12" id=frmCompare name=frmCompare method="post">  
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Enter API endpoint to pull products from:</span>
                    </div>
                    
                    <input type="text" class="form-control" placeholder="URL" name="url" id="url" value="@Html.Raw(Model.url)">
                    <div class="input-group-append">
                        <button class="btn btn-secondary" asp-page-handler="PullProducts" type="submit">
                            Pull Products from Clinics
                        </button>
                    </div>
                </div>
            </form>

             <div class="row pt-5">
                 <ul>
                    @{
                        if (!string.IsNullOrEmpty(Model.jSonResult))
                        {
                            IList<JToken> results;
                            var token = JToken.Parse(Model.jSonResult);
                            if (token is JArray)
                            {
                                JArray jsonArray = JArray.Parse(Model.jSonResult);
                                dynamic data = JObject.Parse(jsonArray[0].ToString());
                                results = jsonArray.Children().ToList();
                            }else
                            {
                                JObject jsonArray = JObject.Parse(Model.jSonResult);
                                results = jsonArray.Children().ToList();
                            }
                            foreach (JToken result in results)
                            {
                                @Html.Raw("<li>" + result.First + " -> " + result.First.Next +  " (ALREADY IN DATABASE) </li>");
                            }
                        }
                }
                @*@Html.Raw(Model.jSonResult)*@
                </ul> 
            </div>
        </div>


    </div>
</div>
<partial name="_SecondaryPartial" />

InsecureWebApp/Pages/Products/Details.cshtml
@page "{id:int?}"
@using Microsoft.AspNetCore.Hosting
@using Microsoft.AspNetCore.Routing
@model MicroFocus.InsecureWebApp.Pages.Products.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0"><a asp-page="/Products/Index">Shop</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">@Html.Raw(Model.Product.Name)</strong></div>
        </div>
    </div>
</div>

<div class="site-section-sm">

    <div class="container">

        @if (User.IsInRole("Admin"))
        {
            <p>
                <a asp-page="./Admin/Edit" asp-route-id="@Model.Product.ID">Edit</a> |
                <a asp-page="./Admin/Delete" asp-route-id="@Model.Product.ID">Delete</a>
            </p>
        }

        <div class="row">

            <div class="col-md-5 mr-auto">
                <div class="border text-center">
                    @if (string.IsNullOrEmpty(Model.Product.Image))
                    {
                        <img src="~/img/awaiting-image-sm.png}" alt="Awaiting Image" class="img-thumbnail">

                    }
                    else
                    {
                        @using (Html.BeginForm("ViewPic", "Products", new { sFile = Model.Product.Image }, FormMethod.Get))
                            {
                                <input type="hidden" name="sFile" id="sFile" value="@Model.Product.Image">
                                <button><img src="~/img/products/@Html.Raw(Model.Product.Image)" alt="Image" class="img-fluid p-5"></button> 
                            }
                    }

                </div>
            </div>
            <div class="col-md-6 item-entry">
                <h2 class="text-black">@Model.Product.Name</h2>
                <h5>@Model.Product.Code</h5>
                <div class="product-rating mb-2">
                    <input class="star-rating" id="input-1" type="number" name="input-1" value="@Model.Product.Rating">
                </div>
                <h6>Summary</h6>
                <p>@Model.Product.Summary</p>
                <h6>Description</h6>
                <p>@Model.Product.Description></p>
                <h4 class="price pt-2 pb-4 item-price">
                    @if (Model.Product.OnSale)
                    {
                        <del>
                            <span>@string.Format("{0:C}", Model.Product.Price)</span>
                        </del>
                        <span> &mdash; </span>
                        <span>@string.Format("{0:C}", Model.Product.SalePrice)</span>
                    }
                    else
                    {
                        <span>@string.Format("{0:C}", Model.Product.Price)</span>
                    }
                    @if (Model.Product.InStock)
                    {
                        <span class="badge badge-success">In Stock</span>
                    }
                    else
                    {
                        <span class="badge badge-danger">Out of Stock</span>
                        <span class="badge badge-light text-dark">In stock in @Model.Product.TimeToStock days</span>
                    }
                </h4>

                <div class="cart-add">
                    <div class="mb-5">
                        <div class="input-group mb-3" style="max-width: 180px;">
                            <div class="input-group-prepend">
                                <button id="quantity-minus" class="btn btn-outline-primary js-btn-minus" type="button">&minus;</button>
                            </div>
                            <input class="form-control text-center" value="1" id="quantity-value" readonly>
                            <div class="input-group-append">
                                <button id="quantity-plus" class="btn btn-outline-primary js-btn-plus" type="button">&plus;</button>
                            </div>
                        </div>
                    </div>
                    <p>
                        @if (Model.Product.InStock)
                        {
                            <a id="add-to-cart" href="#" class="buy-now btn btn-sm height-auto px-4 py-3 btn-primary">Add To Cart</a>
                        }
                        else
                        {
                            <a id="add-to-cart" href="#" class="disabled buy-now btn btn-sm height-auto px-4 py-3 btn-primary">Add To Cart</a>
                        }
                    </p>
                </div>

                <div class="confirmation-modal">
                    <div id="checkout-now-modal" role="dialog" aria-hidden="true" class="modal fade" style="display: none;">
                        <div class="modal-dialog modal-md">
                            <div tabindex="-1" role="document" aria-labelledby="checkout-now-header" aria-describedby="checkout-now-modal-body" class="modal-content">
                                <header id="checkout-now-modal-header" class="modal-header">
                                    <h5 class="modal-title">Checkout Now</h5>
                                    <button type="button" aria-label="Close" class="close" data-dismiss="modal">×</button>
                                </header>
                                <div id="checkout-now-modal-body" class="modal-body">
                                    <div class="m-4 text-center">
                                        <h4></h4>
                                    </div>
                                </div>
                                <footer id="checkout-now-modal-footer" class="modal-footer">
                                    <button id="checkout-now" type="button" class="btn btn-primary" data-dismiss="modal">Buy now</button>
                                    <button id="continue-shopping" type="button" class="btn btn-secondary" data-dismiss="modal">Continue shopping</button>
                                </footer>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

<partial name="_SecondaryPartial" />

@section scripts{
    <script src="~/lib/js/star-rating.min.js"></script>
    <script src="~/lib/js/star-rating-theme.min.js"></script>
    <script src="~/js/components/CartAdd.js"></script>
    <script type="text/javascript">
        (function ($) {
            $('.cart-add').CartAdd({ pid: "@Model.Product.ID" });
            $('input[class="star-rating"]').each(function () {
                $(this).rating({ displayOnly: true, showCaption: false, step: 1.0, size: 'xs', theme: 'krajee-fas' });
            });
        })(jQuery);
    </script>
}